name: CI/CD Pipeline

on:
  push:
    branches: [saikat]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      # Docker build
      - name: Build Docker Image
        run: docker build -t grewalt2 .

      # Example: push to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Image
        run: docker tag grewalt2 ${{ secrets.DOCKER_USERNAME }}/grewalt2:latest

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/grewalt2:latest